spring.application.name=budgeting

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true


spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile
spring.ai.openai.chat.options.response-format.type=TEXT
spring.ai.openai.base-url=https://api.groq.com/openai

spring.ai.openai.audio.transcription.options.model=whisper-large-v3-turbo
spring.ai.openai.audio.transcription.options.language=pt
spring.ai.openai.audio.transcription.options.temperature=0
spring.ai.openai.audio.transcription.options.response-format=text
spring.ai.openai.audio.transcription.options.prompt=Audio em portugues brasileiro. \
  Transcrição de gastos financeiros. \
    Identifique: \
        - valor em reais (numero + "reais"):\
        - ação (contei, paguei, comprei):\
        - local ou estabelecimento (mercado, farmacia, restaurante, loja, etc.).

logging.level.org.springframework.ai=DEBUG